#!/usr/bin/env python3

import os
import re
import subprocess
from gradelib import *

r = Runner(save("xv6.out"))

BACKTRACE_RE = r"^(0x000000008[0-9a-f]+)"

def addr2line():
    for f in ['riscv64-unknown-elf-addr2line', 'riscv64-linux-gnu-addr2line', 'addr2line']:
        try:
            devnull = open(os.devnull)
            subprocess.Popen([f], stdout=devnull, stderr=devnull).communicate()
            return f
        except OSError:
            continue
    raise AssertionError('Cannot find the addr2line program')

@test(5, "backtrace smoke test")
def test_backtracetest():
    r.run_qemu(shell_script([
        'bttest'
    ]))
    r.match('^$', no=[".*panic.*"])

@test(0, "running alarmtest")
def test_alarmtest():
    r.run_qemu(shell_script([
        'alarmtest'
    ]))

@test(20, "alarmtest: test0", parent=test_alarmtest)
def test_alarmtest_test0():
    r.match('^test0 passed$')

@test(20, "alarmtest: test1", parent=test_alarmtest)
def test_alarmtest_test1():
    r.match('^\\.?test1 passed$')

@test(10, "alarmtest: test2", parent=test_alarmtest)
def test_alarmtest_test2():
    r.match('^\\.?test2 passed$')

run_tests()
