#!/usr/bin/env python3

"""Generate raw xv6 syscall stubs for picolibc glue."""

SYSCALLS = [
    "exit",
    "read",
    "write",
    "close",
    "fstat",
    "sbrk",
    "open",
    "unlink",
    "getpid",
    "kill",
]


def emit_entry(name):
    symbol = f"__xv6_{name}"
    print(f".global {symbol}")
    print(f"{symbol}:")
    print(f" li a7, SYS_{name}")
    print(" ecall")
    print(" ret")


def main():
    print("# generated by usys_pico.py - do not edit")
    print('#include "kernel/syscall.h"')
    for name in SYSCALLS:
        emit_entry(name)


if __name__ == "__main__":
    main()
