#!/usr/bin/env sh

set -eu

# Generate a clangd-friendly compile_commands.json for xv6.
# This is for code navigation / diagnostics only.
# The real build system is still Makefile.
script_dir=$(CDPATH=; cd "$(dirname "$0")" && pwd -P)
root_dir=$(CDPATH=; cd "$script_dir/.." && pwd -P)

out_file="$root_dir/compile_commands.json"
tmp_file="$out_file.tmp.$$"

trap 'rm -f "$tmp_file"' EXIT HUP INT TERM

lab_mk="$root_dir/conf/lab.mk"

if [ ! -f "$lab_mk" ]; then
echo "error: cannot find $lab_mk" >&2
exit 1
fi

lab=$(
sed -n 's/^[[:space:]]*LAB[[:space:]]*=[[:space:]]*\([^#[:space:]]*\).*/\1/p' "$lab_mk" |
head -n 1
)

if [ -z "$lab" ]; then
echo "error: cannot find LAB in conf/lab.mk" >&2
exit 1
fi

lab_upper=$(printf '%s' "$lab" | tr '[:lower:]' '[:upper:]')
server_port=$(expr "$(id -u)" % 5000 + 25099)

clang=${CLANG:-clang}

lab_flags="-DSOL_${lab_upper} -DLAB_${lab_upper}"

if [ "$lab" = "net" ]; then
lab_flags="$lab_flags -DNET_TESTS_PORT=${server_port}"
fi

# These flags are intentionally clangd-oriented.
# Do not copy every Makefile flag here:
# - -Werror makes editor diagnostics too brittle.
# - -MD is dependency-generation noise.
# - -nostdlib is mostly a link-time concern.
# - -mno-relax / -fno-pie may be unsupported or noisy in clangd.
target="--target=riscv64-unknown-elf"

common_riscv_flags="-Wall -O -fno-omit-frame-pointer -ggdb"
common_riscv_flags="$common_riscv_flags $lab_flags"
common_riscv_flags="$common_riscv_flags -mcmodel=medany -ffreestanding -fno-common"
common_riscv_flags="$common_riscv_flags -fno-stack-protector"
common_riscv_flags="$common_riscv_flags -I."

kernel_c_flags="$common_riscv_flags"
user_c_flags="$common_riscv_flags"
pico_c_flags="$common_riscv_flags -isystem opt/picolibc-rv64-xv6/include -march=rv64gc -mabi=lp64"
pico_s_flags="$target -x assembler-with-cpp $common_riscv_flags -march=rv64gc -mabi=lp64"

kernel_s_flags="$target -x assembler-with-cpp -I. -Ikernel"
user_s_flags="$target -x assembler-with-cpp -I. -Ikernel"
user_initcode_flags="$target -x assembler-with-cpp $common_riscv_flags -march=rv64g -nostdinc -Ikernel"

mkfs_c_flags="-Wall -I. $lab_flags"

escape_json() {

# Good enough for normal repository paths and command lines.
# It escapes backslashes and double quotes.
printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

first=1

write_entry() {
file_path=$1
command=$2

if [ "$first" = 0 ]; then
printf ',\n' >> "$tmp_file"
fi
first=0

printf '  {\n' >> "$tmp_file"
printf '    "directory": "%s",\n' "$(escape_json "$root_dir")" >> "$tmp_file"
printf '    "file": "%s",\n' "$(escape_json "$file_path")" >> "$tmp_file"
printf '    "command": "%s"\n' "$(escape_json "$command")" >> "$tmp_file"
printf '  }' >> "$tmp_file"
}

printf '[\n' > "$tmp_file"

for file in "$root_dir"/kernel/*.c; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $target $kernel_c_flags -c $rel"
done

for file in "$root_dir"/kernel/*.S; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $kernel_s_flags -c $rel"
done

for file in "$root_dir"/user/*.c; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $target $user_c_flags -c $rel"
done

for file in "$root_dir"/user/pico/*.c; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $target $pico_c_flags -c $rel"
done

for rel in user/echo.c user/sleep.c; do
if [ -f "$root_dir/$rel" ]; then
write_entry "$rel" "$clang $target $pico_c_flags -DPICOLIBC_USER -c $rel"
fi
done

for file in "$root_dir"/user/*.S; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}

# user/usys.S is generated by user/usys.pl, so do not treat it as a primary source.
if [ "$rel" = "user/usys.S" ]; then
continue
fi

if [ "$rel" = "user/initcode.S" ]; then
write_entry "$rel" "$clang $user_initcode_flags -c $rel"
else
write_entry "$rel" "$clang $user_s_flags -c $rel"
fi
done

for file in "$root_dir"/user/pico/*.S; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $pico_s_flags -c $rel"
done

for file in "$root_dir"/mkfs/*.c; do
[ -f "$file" ] || continue
rel=${file#"$root_dir"/}
write_entry "$rel" "$clang $mkfs_c_flags -c $rel"
done

printf '\n]\n' >> "$tmp_file"

meson_compile_commands="$root_dir/build/picolibc-rv64/compile_commands.json"
if [ -f "$meson_compile_commands" ]; then
python3 - "$tmp_file" "$meson_compile_commands" <<'PY'
import json
import sys
from pathlib import Path

out_path = Path(sys.argv[1])
meson_path = Path(sys.argv[2])

entries = json.loads(out_path.read_text())
entries.extend(json.loads(meson_path.read_text()))
out_path.write_text(json.dumps(entries, indent=2) + "\n")
PY
fi

mv "$tmp_file" "$out_file"
trap - EXIT HUP INT TERM

echo "generated $out_file"
