#!/ usr / bin / perl - w

# 生成 usys.S，即用户态系统调用桩（stub）。
# 每个系统调用对应一段汇编：将 syscall 编号装入 a7 → ecall → ret。
# ecall 指令使 CPU 从 U-mode 陷入 M-mode（经 trampoline），
# 最终由内核 usertrap() → syscall() 处理。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");
entry("sigalarm");
entry("sigreturn");
entry("symlink");
entry("mmap");
entry("munmap");
entry("connect");
entry("pgaccess");
