#!/usr/bin/env python3

"""Generate user-space syscall stubs."""

SYSCALLS = [
    "fork",
    "exit",
    "wait",
    "pipe",
    "read",
    "write",
    "close",
    "kill",
    "exec",
    "open",
    "mknod",
    "unlink",
    "fstat",
    "link",
    "mkdir",
    "chdir",
    "dup",
    "getpid",
    "sbrk",
    "sleep",
    "uptime",
    "trace",
    "sysinfo",
    "sigalarm",
    "sigreturn",
    "symlink",
    "mmap",
    "munmap",
    "connect",
    "pgaccess",
    "lseek",
    "dup2",
    "getdents",
]


def emit_entry(name):
    print(f".global {name}")
    print(f"{name}:")
    print(f" li a7, SYS_{name}")
    print(" ecall")
    print(" ret")


def main():
    print("# generated by usys.py - do not edit")
    print('#include "kernel/syscall.h"')
    for name in SYSCALLS:
        emit_entry(name)


if __name__ == "__main__":
    main()
